services:
  app:
    container_name: self-service
    build: .
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT: ${DATABASE_CONNECTION_TIMEOUT}
      PORT: ${PORT}
      MERCADO_PAGO_API_URL: ${MERCADO_PAGO_API_URL}
      MERCADO_PAGO_API_TOKEN: ${MERCADO_PAGO_API_TOKEN}
      NOTIFICATION_WEBHOOK: ${NOTIFICATION_WEBHOOK}

  db:
    container_name: postgres
    image: postgres:16
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
