kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: self-service
  namespace: default
spec:
  project: default
  source:
    path: infrastructure\gitops\argocd\workloads\self-service
    repoURL: 'https://github.com/cloud-burger'
    targetRevision: feature/kubernetes
  destination:
    namespace: self-service
    server: 'https://kubernetes.default.svc'