---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: self-service-postgres
  name: self-service-postgres
  namespace: self-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-service-postgres
  template:
    metadata:
      labels:
        app: self-service-postgres
    spec:
      initContainers:
      - name: clone-migrations
        image: alpine:latest
        command: ['sh', '-c', 'apk add git && git clone https://github.com/cloud-burger/self-service.git && cp self-service/migrations/init.sql /docker-entrypoint-initdb.d']
        volumeMounts:
          - name: migrations
            mountPath: /docker-entrypoint-initdb.d
      containers:
      - image: postgres:16
        name: self-service-postgres
        env:
          - name: POSTGRES_USER
            value: superuser
          - name: POSTGRES_PASSWORD
            value: supersecret
        volumeMounts:
          - name: data
            mountPath: /dev/shm
          - name: migrations
            mountPath: /docker-entrypoint-initdb.d
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
      volumes:
        - name: data
          emptyDir:
            medium: "Memory"
        - name: migrations
          emptyDir:
            medium: "Memory"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: self-service-postgres
  name: self-service-postgres
  namespace: self-service
spec:
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: http
  selector:
    app: self-service-postgres
  type: ClusterIP