---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: self-service-backend
  name: self-service-backend
  namespace: self-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-service-backend
  template:
    metadata:
      labels:
        app: self-service-backend
    spec:
      containers:
      - image: gabrielmadrid/self-service-backend:latest
        name: self-service-backend
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: PORT
            value: "8080"
          - name: DATABASE_HOST
            value: self-service-postgres.svc.cluster.local
          - name: DATABASE_USERNAME
            value: superuser
          - name: DATABASE_PASSWORD
            value: supersecret
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: self_service
          - name: DATABASE_CONNECTION_TIMEOUT
            value: "120000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: self-service-backend
  name: self-service-backend
  namespace: self-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: self-service-backend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: self-service-backend
  namespace: self-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-service-backend
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60