---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    path: manifests/charts/istio-operator
    targetRevision: 1.23.2
  destination:
    name: "in-cluster"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  profile: demo
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: istio-ingressgateway
          app: istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"